# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # master node
  config.vm.define :master do |master|
    master.vm.box = "debian/buster64"
    master.vm.box_check_update = false
    master.vm.provider "virtualbox"

    master.vm.provider 'virtualbox' do |vb|
        vb.gui = false
        vb.memory = '2048'
        vb.name = 'ansible-dev-master'
    end

    # config.vm.hostname = 'dev.vagrant.ansible-dev'
    master.vm.hostname = 'ansible-dev-master'
    master.vm.network "private_network", ip: "192.168.56.111"
  end

  # worker node
  (1..2).each do |i|
    config.vm.define "node#{i}" do |nodex|
        nodex.vm.box = "debian/buster64"
        nodex.vm.box_check_update = false
        nodex.vm.provider "virtualbox"

        nodex.vm.provider 'virtualbox' do |vb|
            vb.gui = false
            vb.memory = '2048'
            vb.name = "ansible-dev-node#{i}"
        end

        # config.vm.hostname = 'dev.vagrant.ansible-dev'
        nodex.vm.hostname = 'ansible-dev-node'
        nodex.vm.network "private_network", ip: "192.168.56.1#{i}"
    end
  end

  config.vm.provision 'shell', inline: <<-SHELL 
    sed -i 's@http://deb.debian.org/debian@http://ftp.lanet.kr@' /etc/apt/sources.list
    sed -i 's@http://ftp.kr.debian.org/debian@http://ftp.lanet.kr@' /etc/apt/sources.list
    apt-get update -qq && apt-get upgrade -y
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
