Vagrant.configure("2") do |config|

    # master node
    config.vm.define :master do |master|
        master.vm.box = "bento/ubuntu-18.04"
        master.vm.box_check_update = false
        master.vm.provider "virtualbox"

        master.vm.provider 'virtualbox' do |vb|
            vb.gui = false
            vb.memory = '2048'
            vb.name = 'ansible-dev-master'
        end

        # config.vm.hostname = 'dev.vagrant.ansible-dev'
        master.vm.hostname = 'ansible-dev'
        master.vm.network "private_network", ip: "192.168.56.110"
    end

    (1..2).each do |i|
        config.vm.define "node#{i}" do |nodex|
            nodex.vm.box = "bento/ubuntu-18.04"
            nodex.vm.box_check_update = false
            nodex.vm.provider "virtualbox"
    
            nodex.vm.provider 'virtualbox' do |vb|
                vb.gui = false
                vb.memory = '2048'
                vb.name = "ansible-dev-node#{i}"
            end
    
            # config.vm.hostname = 'dev.vagrant.ansible-dev'
            nodex.vm.hostname = 'ansible-dev'
            nodex.vm.network "private_network", ip: "192.168.56.11#{i}"
        end
    end
    
    config.vm.provision 'shell', inline: <<-SHELL
        sed -i 's@http://archive.ubuntu.com/@http://mirror.kakao.com/@' /etc/apt/sources.list
        sed -i 's@http://kr.archive.ubuntu.com/@http://mirror.kakao.com/@' /etc/apt/sources.list
        #apt-get update -qq && apt-get upgrade -y
    SHELL

end
