# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "dev.vagrant.test-ub"
  config.vm.box_check_update = false

  # config.vm.network "private_network", ip: "192.168.56.201"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  #config.vm.network "private_network", :ip => "192.168.56.201", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2
  config.vm.network "private_network", :ip => "192.168.56.201", :type => 'dhcp', :name => 'vboxnet0'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '2048'
    vb.name = 'test-ub'
  end

  config.vm.provision 'shell', inline: <<-SHELL
    # default
#    sed -i 's/http:\/\/archive.ubuntu.com\//http:\/\/ftp.daumkakao.com\//' /etc/apt/sources.list
    sed -i 's@http://archive.ubuntu.com/@http://ftp.daumkakao.com/@' /etc/apt/sources.list
    # apt-get clean && apt-get update -qq && apt-get upgrade -y
    # apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev
    # docker
    # apt-get install -y docker docker.io docker-compose
    # ruby
    ## environment

    sudo -H -u ubuntu git clone https://github.com/rbenv/rbenv.git /home/ubuntu/.rbenv
    sudo -H -u ubuntu git clone https://github.com/rbenv/ruby-build.git /home/ubuntu/.rbenv/plugins/ruby-build
    ba
    sudo -H -u ubuntu echo 'eval "$(rbenv init -)"' >> /home/ubuntu/.bashrc
    # source ~/.bashrc
    sudo -H -u ubuntu source ~/.bashrc
    ## ruby install
    sudo -H -u ubuntu rbenv install 2.3.3
    sudo -H -u ubuntu rbenv global 2.3.3
    sudo -H -u ubuntu gem install rails bundler
    ## chef etc
    sudo -H -u ubuntu gem install knife-solo chef knife berkshelf
    ## chef-dk
    # wget https://packages.chef.io/files/stable/chefdk/2.0.26/ubuntu/16.04/chefdk_2.0.26-1_amd64.deb
    # dpkg -i chefdk_2.0.26-1_amd64.deb
  SHELL

  config.vm.provision 'shell', privileged: false, inline: <<-SHELL
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    source ~/.bashrc
    rbenv install 2.3.3
    rbenv global 2.3.3
    gem update --system
    yes | gem update
    gem install rdoc rails bundler pg
    ## chef etc
    gem install knife-solo chef knife berkshelf
  SHELL

  # vagrant plugin
  ## omnibus
  config.omnibus.chef_version = :latest
  config.omnibus.cache_packages = false
  ## berkshelf
  # config.berkshelf.enabled = true
  # config.berkshelf.berksfile_path = './chef-work/Berksfile'

  # config.vm.provision :chef_client do |chef|
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['./chef-work']
    chef.add_recipe 'chef-work'
    chef.run_list = [
      'recipe[chef-work:mysql]',
    ]
    # chef.cookbooks_path = ['./cookbooks']
    # chef.run_list = [
    #     "recipe[apache2]",
    #     "recipe[apache2::mod_php5]",
    #     "recipe[mysql::client]",
    #     "recipe[mysql::server]",
    #     "recipe[php]",
    #     "recipe[php::module_mysql]"
    # ]
    # chef.add_recipe "mysql::server"
  end
end
