- geerlingguy.security
- geerlingguy.swap
- geerlingguy.docker
- src: https://github.com/ScriptonBasestar-devops/ansible-role-kubernetes
- geerlingguy.git
- geerlingguy.haproxy
- geerlingguy.nginx
# - geerlingguy.java
