---
- name: ansible-default
  hosts: all
  become: yes

  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    # - name: Change Ubuntu repo1
    #   shell: sed -i 's@http://archive.ubuntu.com/@http://mirror.kakao.com/@' /etc/apt/sources.list
    # - name: Change Ubuntu repo2
    #   shell: sed -i 's@http://kr.archive.ubuntu.com/@http://mirror.kakao.com/@' /etc/apt/sources.list
    - setup: # aka gather_facts


- name: ansible-redis
  hosts: all
  become: yes

  vars:
    - redis_bind: 0.0.0.0
      redis_password: passw0rd
      redis_port: 6379

  roles:
    - DavidWittman.redis


- name: ansible-mysql
  hosts: all
  become: yes
  vars:
    - mysql_root_password: super-secure-password
      # mysql_databases:
      #   - name: example_db
      #     encoding: latin1
      #     collation: latin1_general_ci
      # mysql_users:
      #   - name: example_user
      #     host: "%"
      #     password: similarly-secure-password
      #     priv: "example_db.*:ALL"
  roles:
    - role: geerlingguy.mysql
      become: yes

# https://galaxy.ansible.com/geerlingguy/git
      # geerlingguy.haproxy
      # geerlingguy.nginx