# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.hostname = 'dev.vagrant.mysql-ub'
  config.vm.box_check_update = true

  config.vm.network 'private_network', ip: '192.168.56.202', type: 'dhcp', name: 'vboxnet0'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '2048'
    vb.name = 'mysql-ub'
  end

  config.vm.provision 'shell', inline: <<-SHELL
    sed -i 's@http://archive.ubuntu.com/@http://ftp.daumkakao.com/@' /etc/apt/sources.list
    apt-get clean && apt-get update -qq && apt-get upgrade -y
  SHELL

  config.omnibus.chef_version = :latest
  # config.berkshelf.enabled = true
  # config.berkshelf.berksfile_path = '../chef-work/Berksfile'

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['../cookbooks']
    chef.add_recipe 'chef-work'
    chef.add_recipe 'chef-work::mysql'
    chef.run_list = [
      'mysql',
    ]
  end
end
