# source "https://api.berkshelf.com"
# source chef_server: "https://mychefserver.example.com/organizations/one", client_name: "one-client", client_key: "/path/to/one-client.pem"
# site :opscode
# source :chef_server
source 'https://supermarket.chef.io'


cookbook 'build-essential', '~> 8.2.1'
cookbook 'apt', '~> 7.1.1'
cookbook 'iptables'
cookbook 'apache2'
cookbook 'php'
cookbook 'nginx', '~> 8.1.6'
cookbook 'mysql', '~> 8.5.1'
# cookbook 'redis', '~> 3.0.4'
# cookbook 'redis-omnibus', '~> 2.1.0'
# cookbook 'runit', '~> 0.14.13', path: '../runit'
# cookbook 'sb-metachef', '~> 3.0.4', git: 'https://github.com/ScriptonBasestar-infra/sb-metachef-cookbook.git'
# cookbook 'sb-redis', '~> 3.0.4', git: 'https://github.com/ScriptonBasestar-infra/sb-redis-cookbook.git'
# cookbook 'erlang', '~> 7.0.0'
# cookbook 'blp-redis', '~> 3.0.0', git: 'https://github.com/ScriptonBasestar-infra/redis-cookbook.git'
cookbook 'rabbitmq', '~> 5.6.1'
# cookbook 'rabbitmq', '~> 5.6.2', git: 'https://github.com/rabbitmq/chef-cookbook.git'
cookbook 'kafka', '~> 2.2.2'