# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = 'dev.vagrant.ub16'
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.56.111"


  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '4096'
    vb.name = 'ub16'
  end
  
  config.vm.provision 'shell', inline: <<-SHELL
    # sed -i 's/http:\/\/archive.ubuntu.com\//http:\/\/ftp.daumkakao.com\//' /etc/apt/sources.list
    sed -i 's@http://archive.ubuntu.com/@http://mirror.kakao.com/@' /etc/apt/sources.list
    sed -i 's@http://kr.archive.ubuntu.com/@http://mirror.kakao.com/@' /etc/apt/sources.list
    apt-get update -qq && apt-get upgrade -y
    apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev

    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
    sudo apt-get update && sudo apt-get install google-cloud-sdk
  SHELL

  config.vm.provision 'shell', privileged: false, inline: <<-SHELL
    # ruby
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    # echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
    source ~/.bashrc

    rbenv install 2.5.1
    rbenv global 2.5.1
    gem update --system
    yes | gem update
    gem install rdoc rails pg bundler
  SHELL

end
