# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  # config.vm.hostname = 'dev.vagrant.ansible-work'
  config.vm.hostname = 'ansible-work'
  config.vm.box_check_update = false
  config.vm.provider "virtualbox"

  config.vm.network "private_network", ip: "192.168.56.111"

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '4096'
    vb.name = 'ansible-work'
  end


  config.vm.provision 'shell', inline: <<-SHELL
    sed -i 's@http://archive.ubuntu.com/@http://mirror.kakao.com/@' /etc/apt/sources.list
    sed -i 's@http://kr.archive.ubuntu.com/@http://mirror.kakao.com/@' /etc/apt/sources.list
    apt-get update -qq && apt-get upgrade -y
    # apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev
    # 신 software-properties-common 구 python-software-properties
  SHELL

  # vagrant plugin
  ## ansible

  
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end

end
