---
# tasks file for common
- name: install common tools
  apt: 
    name: {{item}}
    update_cache: true
    state: present
  with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - libffi-dev
    - software-properties-common
