# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#  config.vm.box = "ubuntu/bionic64"
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network 'private_network', ip: '192.168.56.101', name: 'vboxnet0'

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
#    apt-get install -y ruby
  SHELL
end
